global:
  scrape_interval: 1s
  evaluation_interval: 1s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'metrics-server'
    static_configs:
      - targets: ['metrics-server:8080']
    scrape_interval: 1s
    metrics_path: /metrics
    honor_labels: true
